task: winogrande_uk
dataset_path: INSAIT-Institute/winogrande_ukr
output_type: generate_until
training_split: validation
validation_split: validation
test_split: validation
doc_to_text: !function preprocess_winogrande.doc_to_text_generate
doc_to_target: !function preprocess_winogrande.doc_to_target_generate
should_decontaminate: true
doc_to_decontamination_query: sentence
num_fewshot: 0
generation_kwargs:
  max_gen_toks: 50
  until:
    - "\n"
    - "."
  do_sample: false
  temperature: 0.0
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
filter_list:
  - name: "flexible-extract"
    filter:
      - function: "regex"
        regex_pattern: "([ABab])"
      - function: "take_first"
      - function: "uppercase"
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true
