task: hellaswag_uk
dataset_path: INSAIT-Institute/hellaswag_ukr
output_type: generate_until
training_split: validation
validation_split: validation
test_split: validation
process_docs: !function utils.process_docs
doc_to_text: !function utils.doc_to_text_generate
doc_to_target: !function utils.doc_to_target_generate
num_fewshot: 0
generation_kwargs:
  max_gen_toks: 50
  until:
    - "\n"
    - "."
  do_sample: false
  temperature: 0.0
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
filter_list:
  - name: "flexible-extract"
    filter:
      - function: "regex"
        regex_pattern: "([A-Da-d])"
      - function: "take_first"
      - function: "uppercase"
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true
