task: arc_easy_uk
dataset_path: INSAIT-Institute/arc-easy_ukr
output_type: generate_until
training_split: train
validation_split: validation
test_split: test
fewshot_split: train
doc_to_text: !function utils.doc_to_text_arc
doc_to_target: !function utils.doc_to_target_arc
should_decontaminate: true
doc_to_decontamination_query: "Питання: {{question}}"
num_fewshot: 0
generation_kwargs:
  max_gen_toks: 50
  until:
    - "\n"
    - "."
  do_sample: false
  temperature: 0.0
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
filter_list:
  - name: "flexible-extract"
    filter:
      - function: "regex"
        regex_pattern: "([A-Da-d])"
      - function: "take_first"
      - function: "uppercase"
metadata:
  version: 2.0
