task: belebele_uk
dataset_path: facebook/belebele
dataset_name: ukr_Cyrl
output_type: generate_until
test_split: test
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
num_fewshot: 0
generation_kwargs:
  max_gen_toks: 50
  until:
    - "\n"
    - "."
  do_sample: false
  temperature: 0.0
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
filter_list:
  - name: "flexible-extract"
    filter:
      - function: "regex"
        regex_pattern: "([1-4])"
      - function: "take_first"
metadata:
  version: 2.0
